### ISSUE TITLE
.RDatas instead of .Rdatas

### ISSUE THREAD

**Issue by nalimilan** [daroczig/saves#3]
One small issue that worries me while using your very handy package (I discovered it today - thanks!) is that the default filename ends with .Rdata. I saw you're using the same extension in your posts when calling save(), but the default in R is .RData, which an uppercase D. That's for example what save.image() uses when saving to ".RData".

So that's a little detail, easy to fix, but I think it's worth it since that will avoid introducing confusion. Case is already complicated enough to get right!

**Comment by daroczig** [comment]
You are right, thank you very much for your kind feedback.

I have changed file extensions accordingly in my local git now, will be available in github/CRAN soon (after I would have checked/sorted out other issues as well with some testing - in max. 1-2 days). Therefor I leave this ticket open, will report back here.

And yes, case is already complicated enought :)
