### ISSUE TITLE
Fix use of tempdir()

### ISSUE THREAD

**Issue by nalimilan** [daroczig/saves#4]
save() doesn't use tempdir() correctly, which leads to warnings when calling it several times : the same file is being overwritten again and again. If you look at ?tempdir, you'll see that you shouldn't do:
    tmp <- paste(tempdir(), '/saves.temp', sep='')
but
    tmp <- tempfile('saves', fileext='.RDatas')

The reason is, tempdir() always returns the same dir, and that's why tempfile() exists: to find a unique name. This also avoids security issues, as malicious programs could trick you into writing to some weird place be creating a symlink at the place they know you'll create the temp file (remember, most of the time, any user on the system can write to temp directories).

**Comment by nalimilan** [comment]
BTW, since you need to create a few files in a row, you can pass a vector of names, and tmpfile() will return the vector of actual file names. So you can iterate over that for save(), and pass that directly to tar.

**Comment by daroczig** [comment]
Yes, that was an ugly solution :)
I have changed that referenced line to avoid conflicting problems.

I did not take your other suggestion (using `tempfile` for file names), as I think it is a good idea to store variable names in the compressed archive's `.RData` files' names. It might be dummy, but sometime I would like to open an `RDatas` file by hand or uncompress it for some reason, it would be great if I would not what is inside those files :)

**Comment by nalimilan** [comment]
Yeah, makes sense. Thanks!
