### ISSUE TITLE
Use the same semantics as save()

### ISSUE THREAD

**Issue by nalimilan** [daroczig/saves#5]
saves() takes the name of the data frame/list as argument. save(), on the contrary, takes the real object, but has a 'list' argument that takes the name(s). I think saves() should do the same, for consistency (rm() also uses this scheme). You just need to make it clear how to pass names in the documentation, as it's really something handy when working with several data frames.

**Comment by daroczig** [comment]
A good idea/hint indeed, I have just commited a new version of the package where the `saves()` function takes R objects as argument primary, but the `list` parameter option is also working. Thanks for pointing my attention for this!
